import React from 'react';
import GalleryPrototype from "./GalleryPrototype";

export default class MainCakesGallery extends React.Component{
    constructor(props) {
        super(props);
        this.state = {
            gallery: [
                {
                    image:"imgs/cake11.jpg",
                    position:0,
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake03.jpg",
                    position:0,
                    height:"100%",
                    width:"auto"
                },
                {
                    image:"imgs/cake06.jpg",
                    position:0,
                    height:"100%",
                    width:"auto"
                },
                {
                    image:"imgs/cake04.jpg",
                    position:0,
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake10.jpg",
                    position:"32px",
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake17.jpg",
                    position:"-30px",
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake07.jpg",
                    position:"10px",
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake12.jpg",
                    position:0,
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake05.jpg",
                    position:0,
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake18.jpg",
                    position:0,
                    height:"100%",
                    width:"auto"
                },
                {
                    image:"imgs/cake08.jpg",
                    position:0,
                    height:"100%",
                    width:"auto"
                },
                {
                    image:"imgs/cake15.jpg",
                    position:0,
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake02.jpg",
                    position:0,
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake16.jpg",
                    position:0,
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake14.jpg",
                    position:"10px",
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake19.jpg",
                    position:0,
                    height:"100%",
                    width:"auto"
                },
                {
                    image:"imgs/cake09.jpg",
                    position:"-20px",
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake01.jpg",
                    position:"25px",
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake13.jpg",
                    position:0,
                    height:"auto",
                    width:"100%"
                },
                {
                    image:"imgs/cake20.jpg",
                    position:0,
                    height:"auto",
                    width:"100%"
                },
            ]
        }
    }
    render() {
        const gallery = this.state.gallery;
        return (
            <GalleryPrototype images={gallery}/>
        )
    }
}